# Generated by Django 2.1.7 on 2019-03-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recurso_fechaasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='fechaAsignacion',
            field=models.DateField(auto_now=True),
        ),
    ]
