# Generated by Django 2.1.7 on 2019-03-22 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recurso_fechaasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='marca',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
