# Generated by Django 2.1.7 on 2019-03-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recurso_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargado',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TipoEncargado'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Encargado'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Proveedor'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TipoRecurso'),
        ),
    ]
